apiVersion: v1
kind: Namespace
metadata:
  name: tbsen
---

# backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbsen-backend
  namespace: tbsen
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/banseokdev/tbsen-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8081
          name: agent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: tbsen
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  - name: agent
    port: 8081
    targetPort: 8081
---

# Frontend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tbsen-frontend
  namespace: tbsen
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/banseokdev/tbsen-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf-vol
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-conf-vol
        configMap:
          name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: tbsen
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: tbsen
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api {
            proxy_pass http://backend-svc:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }